### PR TITLE
Add pagination on reviews page

### LINKED ISSUE #49: Add pagination on review pages
Review pages are currently showing all reviews at once.

Add pagination support on all review pages (common and filtered by subjects)

This might be helpful: https://www.npmjs.com/package/express-paginate

### PR DESCRIPTION
**Pull request by amenat**
Add pagination on reviews view.
Basic implementation:
 - Highlight current page
 - Show next/prev buttons if available.

Possible improvements:
 - Show first/last page with ellipsis in between.
 - Ability to select # of reviews / page. Right now defaults to 10 and can be changed by modifying GET parameter.

closes #49

### CODE REVIEW

**Comment by BlairCurrey** [comment]
This breaks the review page for individual courses. Shows a 500 error when you click on a course in the 'Courses' table: 

> ReferenceError: Cannot access 'sqlquery' before initialization
>     at C:\Users\Blair\Documents\Programming\compass\routes\reviews.js:24:3

Lines 23-25 appear to be older version of same code that is reimplemented in lines 55-58. It appears lines 23-25 can just be deleted.

After deleting them and clicking on a course this is the view:
image

It shows another page and 'next' when there shouldn't be another page. Seems the current `pageCount` just works with all reviews.

**Comment by BlairCurrey** [comment]
Also not sure if not nesting everything inside the first db call could lead to any issues. Works fine for me but I think the `itemCount` declaration in the first `db` call could theoretically execute after the proceeding code (including `itemCount` reference).

**Comment by amenat** [comment]
> This breaks the review page for individual courses. Shows a 500 error when you click on a course in the 'Courses' table:
> 
> > ReferenceError: Cannot access 'sqlquery' before initialization
> > at C:\Users\Blair\Documents\Programming\compass\routes\reviews.js:24:3
> 
> Lines 23-25 appear to be older version of same code that is reimplemented in lines 55-58. It appears lines 23-25 can just be deleted.
> 

It's required. It should've been `countQuery` instead of `sqlquery`. Fixing it.

**Comment by BlairCurrey** [comment]
looks good

**Pull request merged**
